### ISSUE TITLE
Integrate/recommend svgo for ~65% size reduction

### ISSUE THREAD

**Issue by makew0rld** [xyproto/png2svg#2]
Using [svgo](https://github.com/svg/svgo) reduces the demo files on the README by about 65%. Maybe you should recommend it, or even make use of it in your code, if the user has it installed?

```
❯ svgo -i spaceships.svg -o spaceships.min.svg                               

spaceships.svg:
Done in 992 ms!
186.949 KiB - 63.3% = 68.553 KiB
```

```
❯ svgo -i rainforest4096.svg -o rainforest4096.min.svg 

rainforest4096.svg:
Done in 294565 ms!
3051.344 KiB - 64.4% = 1086.735 KiB
```

After analyzing the source files (you'll find the `--pretty` option useful for that), it looks like it's basically just converting all your `rect`s into `path`s. Possibly something this code could do on its own.

**Comment by xyproto** [comment]
That's a nice find! Thank you.

I'll make sure to mention it and/or try to implement a similar optimization using `path`s.
