### ISSUE TITLE
support Apple Silicon (M1) 

### ISSUE THREAD

**Issue by youkale** [xyproto/png2svg#3]
Compile support Apple M1

**Comment by xyproto** [comment]
Thanks for reporting.

I don't have an M1 to test on, unfortunately.

Does it work with the latest version of the Go compiler, version 1.18?

**Comment by vesper8** [comment]
I'm on an M1 and I just installed `go` using `brew`

When I run `go install github.com/xyproto/png2svg/cmd/png2svg@latest`

I get

```
go: downloading github.com/xyproto/png2svg v1.5.2
go: downloading github.com/xyproto/tinysvg v1.0.1
```

Is it supposed to say more than this? It doesn't seem to have installed it. It's certainly not in my path and I can't run it. Maybe I need to add go to my path first?

**Comment by vesper8** [comment]
Got it to work.. it was just a path issue. Here are the full steps I did

```
mkdir -p $HOME/go/{bin,src,pkg}

# add the following 3 lines to your .bashrc / .zshrc
export GOPATH=$HOME/go
export GOROOT="$(brew --prefix golang)/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"

# install go
brew install golang

#install png2svg
go install github.com/xyproto/png2svg/cmd/png2svg@latest
```


Open a new tab, or source your .bashrc/.zshrc


Then png2svg will work

**Comment by xyproto** [comment]
Thanks for testing.

Yes, it's part of the setup of the Go compiler on macOS/Homebrew. On Linux, none of the above is needed.

Oh, and `GOPATH` is `~/go` by default, so there should be no need to set it to `$HOME/go`.

I'll consider adding a note about macOS/Homebrew to the README, even though it's not specific to this project.

I'm glad it's working on M1!
