### ISSUE TITLE
Is there deb format package for png2svg?

### ISSUE THREAD

**Issue by atzlinux** [xyproto/png2svg#4]
The png2svg is good tools, I like it.

Is there deb format package for png2svg already?

Perhaps I can make a deb package for png2svg.

**Comment by xyproto** [comment]
As far as I know, there is no Debian package available for `png2svg` yet.

If a Debian maintainer packaged it for Debian, or if someone created a PPA for Ubuntu, that would be great.

There is an unofficial Arch Linux package available here: https://aur.archlinux.org/packages/png2svg

Do you believe that every open source project should maintain its own packages for all popular Linux distros, as opposed to all Linux distros maintaining their own packages for various open source projects? I think perhaps I'm leaning towards the latter. But, if you think it would be helpful, then by all means, create a PR and I'll review it. :)

**Comment by xyproto** [comment]
Thank you.

As far as I know, there is no Debian package available for `png2svg` yet.

If a Debian maintainer packaged it for Debian, or if someone created a PPA for Ubuntu, that would be great.

There is an unofficial Arch Linux package available here: https://aur.archlinux.org/packages/png2svg

Do you believe that every open source project should maintain its own packages for all popular Linux distros, as opposed to all Linux distros maintaining their own packages for various open source projects? I think perhaps I'm leaning towards the latter. But, if you think it would be helpful, then by all means, create a PR and I'll review it. :)

**Comment by atzlinux** [comment]
Good News!  The png2svg is the official Debian package now.

I make the deb package and upload by Adam Borowski.

People can install png2svg from Debian sid now:

https://packages.debian.org/unstable/png2svg

**Comment by xyproto** [comment]
That's excellent! Thank you for doing this. 😄

**Comment by atzlinux** [comment]
You're welcome.

The png2svg is a useful tool.  :+1:
