### ISSUE TITLE
Can there be option choose qty of colors? 

### ISSUE THREAD

**Issue by upgernaut** [xyproto/png2svg#5]
Hi, I'd like to make it work images Canva. So now in order to do it I use - https://www.pngtosvg.com/. If you want to be able to change colors in Canva you put the number of colors. 

Is it possible to do it here? 

I mean not just general limitation 4096  with -l but manual limitation.

**Comment by xyproto** [comment]
I added an `-n` flag for the `png2svg` utility that can be used to reduce the number of colors, using `github.com/xyproto/palgen`. It does not work great for all images and all values of N, but it's a start.

**Comment by xyproto** [comment]
Please test
